/**
 * Isolated per-job workspace under WORKSPACES_DIR/{jobId} with git
 * checkpoints. All agent file access is confined here (path-traversal safe),
 * with a disk-size budget. Designed so a future /v1/games/{id}/edit can
 * reopen an existing workspace and continue from the last checkpoint.
 */
import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { config } from "../config.js";
import { log } from "../logger.js";
import { workspaceDir } from "../jobs.js";
import { TEST_HELPER_SOURCE } from "./staticChecks.js";

export interface Workspace {
  jobId: string;
  root: string;
  engine: "phaser" | "babylon";
}

/**
 * Resolve a relative path inside the workspace; rejects traversal, absolute
 * paths, env/.git access AND symlink escapes: the deepest existing ancestor
 * is realpath'd and must stay inside the workspace, and the target itself
 * must not be a symlink.
 */
export function safePath(ws: Workspace, rel: string): string {
  if (typeof rel !== "string" || rel.includes("\0")) throw new Error("Invalid path");
  const rootReal = fs.existsSync(ws.root) ? fs.realpathSync(ws.root) : ws.root;
  const resolved = path.resolve(rootReal, rel);
  if (resolved !== rootReal && !resolved.startsWith(rootReal + path.sep)) {
    throw new Error(`Path escapes workspace: ${rel}`);
  }
  const base = path.basename(resolved);
  if (base === ".env" || base.startsWith(".env.")) throw new Error("Access to env files is not allowed");
  if (resolved.split(path.sep).includes(".git")) throw new Error("Direct .git access is not allowed");
  // Symlink-safe: realpath the deepest existing ancestor and re-check.
  let probe = resolved;
  while (!fs.existsSync(probe)) probe = path.dirname(probe);
  const probeReal = fs.realpathSync(probe);
  if (probeReal !== rootReal && !probeReal.startsWith(rootReal + path.sep)) {
    throw new Error(`Path escapes workspace via symlink: ${rel}`);
  }
  // The target itself must not be a symlink (no reading/writing through links).
  if (fs.existsSync(resolved) && fs.lstatSync(resolved).isSymbolicLink()) {
    throw new Error(`Symlinks are not allowed: ${rel}`);
  }
  return resolved;
}

export function workspaceSizeMb(ws: Workspace): number {
  let bytes = 0;
  const walk = (dir: string): void => {
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      if (e.name === ".git") continue;
      const p = path.join(dir, e.name);
      if (e.isDirectory()) walk(p);
      else bytes += fs.statSync(p).size;
    }
  };
  if (fs.existsSync(ws.root)) walk(ws.root);
  return bytes / (1024 * 1024);
}

function git(ws: Workspace, args: string[]): string {
  return execFileSync("git", args, {
    cwd: ws.root,
    encoding: "utf8",
    timeout: 20_000,
    env: {
      PATH: process.env.PATH ?? "",
      HOME: ws.root, // keep git away from any host-level config/credentials
      GIT_AUTHOR_NAME: "playlap-agent",
      GIT_AUTHOR_EMAIL: "agent@playlap.local",
      GIT_COMMITTER_NAME: "playlap-agent",
      GIT_COMMITTER_EMAIL: "agent@playlap.local",
    },
  });
}

export function createWorkspace(jobId: string, engine: "phaser" | "babylon"): Workspace {
  const root = workspaceDir(jobId);
  const ws: Workspace = { jobId, root, engine };
  for (const d of ["src", "public", "assets", "tests", "build", "artifacts/screenshots", "vendor"]) {
    fs.mkdirSync(path.join(root, d), { recursive: true });
  }
  // Vendor the approved engine locally so generated games never depend on a
  // CDN at test time (and the Docker image works fully offline).
  const vendorSrc =
    engine === "babylon"
      ? path.join(config.serverRoot, "node_modules", "babylonjs", "babylon.js")
      : path.join(config.serverRoot, "node_modules", "phaser", "dist", "phaser.min.js");
  const vendorDst = path.join(root, "vendor", engine === "babylon" ? "babylon.js" : "phaser.min.js");
  fs.copyFileSync(vendorSrc, vendorDst);
  // Platform test-hook contract helper — the model composes with it instead
  // of reinventing window.__PLAYLAP_TEST__ every game.
  fs.writeFileSync(path.join(root, "src", "playlap-test.js"), TEST_HELPER_SOURCE);
  fs.writeFileSync(
    path.join(root, "package.json"),
    JSON.stringify(
      {
        name: `playlap-game-${jobId.slice(0, 8)}`,
        private: true,
        description: "Generated by Play Lap Game Agent Server",
        playlap: { engine },
      },
      null,
      2,
    ),
  );
  git(ws, ["init", "-q"]);
  git(ws, ["add", "-A"]);
  git(ws, ["commit", "-qm", "workspace scaffold"]);
  log("info", "workspace created", { jobId, engine });
  return ws;
}

export function checkpoint(ws: Workspace, message: string): void {
  try {
    git(ws, ["add", "-A"]);
    git(ws, ["commit", "-qm", message, "--allow-empty"]);
  } catch (err) {
    log("warn", "git checkpoint failed", { jobId: ws.jobId, error: String(err) });
  }
}

export function rollbackToLastCheckpoint(ws: Workspace): void {
  git(ws, ["reset", "--hard", "-q", "HEAD"]);
  git(ws, ["clean", "-fdq", "-e", "artifacts/"]);
}

/** Current checkpoint commit hash (used for regression rollback). */
export function currentCommit(ws: Workspace): string | null {
  try {
    return git(ws, ["rev-parse", "HEAD"]).trim();
  } catch {
    return null;
  }
}

/** Hard-revert the workspace to a known-good checkpoint (QA artifacts kept). */
export function rollbackTo(ws: Workspace, commit: string): void {
  git(ws, ["reset", "--hard", "-q", commit]);
  git(ws, ["clean", "-fdq", "-e", "artifacts/"]);
  log("info", "workspace rolled back to checkpoint", { jobId: ws.jobId, commit });
}

export function enforceSizeLimit(ws: Workspace): void {
  const mb = workspaceSizeMb(ws);
  if (mb > config.maxWorkspaceMb) {
    throw new Error(`Workspace exceeded size limit: ${mb.toFixed(1)}MB > ${config.maxWorkspaceMb}MB`);
  }
}
